version: '3.8'

services:
  backup:
    build:
      context: .
      dockerfile: containers/Containerfile.backup
    container_name: backup-test
    networks:
      - backup-network
    volumes:
      - backup-data:/var/lib/backup
      - backup-logs:/var/log/backup
      - ssh-keys:/shared/ssh-keys
      - ./:/opt/backup-source:ro
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=backup-test-token
      - INFLUXDB_ORG=backup-org
      - INFLUXDB_BUCKET=backup-metrics
      - GRAFANA_URL=http://grafana:3000
      - BACKUP_LOG_LEVEL=DEBUG
      - BACKUP_METRICS_ENABLED=true
    cap_add:
      - NET_RAW
    depends_on:
      - influxdb
            - client1
      - client2
      - client3
      - client4
      - client5

    client1:
    build:
      context: .
      dockerfile: containers/Containerfile.client
    container_name: backup-client1
    hostname: client1
    networks:
      - backup-network
    volumes:
      - client1-data:/home/testuser/data
      - ssh-keys:/shared/ssh-keys
    ports:
      - "2222:22"
    environment:
      - CLIENT_ID=1
      - CLIENT_NAME=client1

  client2:
    build:
      context: .
      dockerfile: containers/Containerfile.client
    container_name: backup-client2
    hostname: client2
    networks:
      - backup-network
    volumes:
      - client2-data:/home/testuser/data
      - ssh-keys:/shared/ssh-keys
    ports:
      - "2223:22"
    environment:
      - CLIENT_ID=2
      - CLIENT_NAME=client2

  client3:
    build:
      context: .
      dockerfile: containers/Containerfile.client
    container_name: backup-client3
    hostname: client3
    networks:
      - backup-network
    volumes:
      - client3-data:/home/testuser/data
      - ssh-keys:/shared/ssh-keys
    ports:
      - "2224:22"
    environment:
      - CLIENT_ID=3
      - CLIENT_NAME=client3

  client4:
    build:
      context: .
      dockerfile: containers/Containerfile.client
    container_name: backup-client4
    hostname: client4
    networks:
      - backup-network
    volumes:
      - client4-data:/home/testuser/data
      - ssh-keys:/shared/ssh-keys
    ports:
      - "2225:22"
    environment:
      - CLIENT_ID=4
      - CLIENT_NAME=client4

  client5:
    build:
      context: .
      dockerfile: containers/Containerfile.client
    container_name: backup-client5
    hostname: client5
    networks:
      - backup-network
    volumes:
      - client5-data:/home/testuser/data
      - ssh-keys:/shared/ssh-keys
    ports:
      - "2226:22"
    environment:
      - CLIENT_ID=5
      - CLIENT_NAME=client5

  influxdb:
    build:
      context: .
      dockerfile: containers/Containerfile.influxdb
    container_name: backup-influxdb
    hostname: influxdb
    networks:
      - backup-network
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=backup-admin-password
      - DOCKER_INFLUXDB_INIT_ORG=backup-org
      - DOCKER_INFLUXDB_INIT_BUCKET=backup-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=backup-test-token

  grafana:
    build:
      context: .
      dockerfile: containers/Containerfile.grafana
    container_name: backup-grafana
    hostname: grafana
    networks:
      - backup-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=backup-grafana-password
    depends_on:
      - influxdb

networks:
  backup-network:
    driver: bridge

volumes:
  backup-data:
  backup-logs:
  ssh-keys:
  influxdb-data:
  influxdb-config:
  grafana-data:
  
  client1-data:
  client2-data:
  client3-data:
  client4-data:
  client5-data:
