version: '3.8'

services:
  backup:
    build:
      context: .
      dockerfile: containers/Containerfile.backup
    container_name: backup-test
    networks:
      - backup-network
    volumes:
      - backup-data:/var/lib/backup
      - backup-logs:/var/log/backup
      - ssh-keys:/shared/ssh-keys
      - ./:/opt/backup-source:ro
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=backup-test-token
      - INFLUXDB_ORG=backup-org
      - INFLUXDB_BUCKET=backup-metrics
      - GRAFANA_URL=http://grafana:3000
      - BACKUP_LOG_LEVEL=DEBUG
      - BACKUP_METRICS_ENABLED=true
    cap_add:
      - NET_RAW
    depends_on:
      - influxdb
      {{CLIENT_DEPENDENCIES}}

  {{CLIENT_SERVICES}}

  influxdb:
    build:
      context: .
      dockerfile: containers/Containerfile.influxdb
    container_name: backup-influxdb
    hostname: influxdb
    networks:
      - backup-network
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=backup-admin-password
      - DOCKER_INFLUXDB_INIT_ORG=backup-org
      - DOCKER_INFLUXDB_INIT_BUCKET=backup-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=backup-test-token

  grafana:
    build:
      context: .
      dockerfile: containers/Containerfile.grafana
    container_name: backup-grafana
    hostname: grafana
    networks:
      - backup-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=backup-grafana-password
    depends_on:
      - influxdb

networks:
  backup-network:
    driver: bridge

volumes:
  backup-data:
  backup-logs:
  ssh-keys:
  influxdb-data:
  influxdb-config:
  grafana-data:
  {{CLIENT_VOLUMES}}
